### PR TITLE
Changes for new version of xgboost

### LINKED ISSUE #28: New xgboost  version
There's a new version coming up and it looks like it breaks xrf: 

```
Package: xrf 0.2.2
Check: tests, Result: ERROR
    Running ‘testthat.R’
  Running the tests in ‘tests/testthat.R’ failed.
  Last 13 lines of output:
     2. └─xrf:::xrf.formula(...)
     3.   └─xgboost::xgboost(...)
     4.     └─xgboost:::process.y.margin.and.objective(...)
    ── Error ('test_model.R:54:3'): model predicts binary outcome ──────────────────
    Error in `process.y.margin.and.objective(y, base_margin, objective, params)`: Got numeric 'y' - supported objectives for this data are: reg:squarederror, reg:squaredlogerror, reg:logistic, reg:pseudohubererror, reg:absoluteerror, reg:quantileerror, count:poisson, reg:gamma, reg:tweedie. Was passed: binary:logistic
    Backtrace:
        ▆
     1. ├─xrf::xrf(...) at test_model.R:54:3
     2. └─xrf:::xrf.formula(...)
     3.   └─xgboost::xgboost(...)
     4.     └─xgboost:::process.y.margin.and.objective(...)
    
    [ FAIL 3 | WARN 44 | SKIP 0 | PASS 12 ]
    Error: Test failures
    Execution halted
```

This is from dmlc/xgboost#11430, which has links to the migration guide and other info. I think they plan on releasing the new verison this month. 

Can I and @EmilHvitfeldt help with this (or with the package in general)?

### PR DESCRIPTION
**Pull request by topepo**
Closes #28 

See dmlc/xgboost#11430

There is no version requirement for xgboost in the description file. Once the new version of xgboost is on CRAN, we can revert c2f87f93dee2faf6f47a7addf0a375af76be14a3 and send xrf to CRAN. 

Main changes here: 

 - xrf requires R >= 4.3 due to xgboost requirement. 😢 
 - Use `xgb.train()` instead of `xgboost()`.
 - Helper function to populate the xgb arguments. 
 - Archive of previous fit to verify backwards compatibility for previously fit models.
 - Small changes to `summary.xrf()`.

### CODE REVIEW

File: R/xrf.R [hunk 1]
```diff
@@ -793,10 +784,13 @@ summary.xrf <- function(object, ...) {
   ))
   cat(paste0('\n\nOriginal Formula:\n\n'))
   cat(smaller_formula(object$base_formula))
-  cat('\n\nTree model:\n\n')
-  show(summary(object$xgb))
-  cat('\n\nGLM:\n\n')
-  show(summary(object$glm))
+  cli::cli_rule("Tree model")
+  cat("\n")
+  print(object$xgb)
```
Comment (holub008) [inline R/xrf.R:789]: Not calling `summary` explicitly here still results in a reasonable summary? i.e. print on the xgboost object delegates to `summary`. Asking because I don't see it mentioned in the migration guide.

File: tests/testthat/test_xgb_1_7_11.R [hunk 2]
```diff
@@ -0,0 +1,11 @@
+# In November 2025, the new version of xgboost has api changes
+# that are breaking changes. See https://github.com/dmlc/xgboost/issues/11430
+# This file uses the current CRAN versions to ensure that prediction
+# works in updated versions of xrf and xgboost.
+
+test_that('prediction works on xgboost versions < 3.0', {
```
Comment (holub008) [inline tests/testthat/test_xgb_1_7_11.R:6]: I'm feeling slow on the uptake-- this test plus `inst/` changes should not be carried forward, right? Unless I'm misunderstanding the package build process, I don't think we'd want include this in every package download.

File: R/xrf.R (hunk 1 above)
Comment (topepo) [reply R/xrf.R:789]: I didn't see any mention of `summary()` in their docs but it errors for me when I tried it.

File: tests/testthat/test_xgb_1_7_11.R (hunk 2 above)
Comment (topepo) [reply tests/testthat/test_xgb_1_7_11.R:6]: Sorry - this wasn't clear. There are some changes to the xgboost objects produced by the new version. These tests are there to ensure that model objects produced prior to version 3 can still be predicted using the new xrf/xgboost versions. 

We can put a deprecation deadline on it (so that it is skipped at some point in the future).

Comment (holub008) [reply tests/testthat/test_xgb_1_7_11.R:6]: Makes sense to assert backwards compatibility, thanks!

Regarding `inst/`-- I'm not familiar with it and its best practices. IME in other langs + [reading here](https://r-pkgs.org/misc.html#sec-misc-inst), it doesn't feel right that we'd include test data / its generation scripts in our production build that gets shipped to end users. Do let me know if I'm misunderstanding its purpose or how `inst/` is conventionally used in R packages.

Comment (topepo) [reply tests/testthat/test_xgb_1_7_11.R:6]: `inst` is a general location for storing items that you don't want direct programmatic access to or for CRAN to focus on. Basically, ancillary objects like the spelling file etc. We also but code and data (i.e. csv files) there in a `data-raw` directory so that we can remake examples. 

The other thing we've done is save test objects [under the `testthat` directory](https://r-pkgs.org/testing-design.html#storing-test-data) or place them in `data`. The latter is good if you want to use the objects for testing and in `@examples` to avoid examples that are expensive to run. 

Anywhere is fine with me. If `inst` has a bad code smell, I think `tests/testthat/fixtures` is a good choice. 

Another alternative is to reference a github raw link but that is problematic in its own way. Tests are now supposed to rely on an internet connection, and that may draw criticism from CRAN.

**Comment by topepo** [comment]
I think XGBoost has sent their new version to CRAN. Would you like me to do anything different for either of these comments?

**Comment by holub008** [comment]
Thank you for the explanations, we are good! I got the failing build alert from CRAN this afternoon, so let's get it out the door. If you add in the xgb version requirement > 3.1.2.1 and cleanup the dev xgb install, I'll merge this in, do some final testing, and publish to CRAN.

I'm so appreciative of your work @topepo !

**Comment by topepo** [comment]
I made those updates. Good luck 🤞
